### ISSUE TITLE
Only Working With Globals Set to True

### ISSUE THREAD

**Issue by theovier** [thomasbrodusch/vitest-fail-on-console#8]
#### Description
The package seems to be only working when the `vitest.config.ts` contains

```ts
test: {
  globals: true
}
```
see https://vitest.dev/config/#globals.

Is there an option to make this plugin work without enabling `globals` explicitly?
If not, it might be worth to adjust the documentation.

### Screenshots / Video / StackTrace
If `globals` is omitted the following error is thrown when a test is run: 
```
ReferenceError: beforeEach is not defined
    at patchConsoleMethod (.../node_modules/vitest-fail-on-console/src/index.ts:121:9)
    at .../node_modules/vitest-fail-on-console/src/index.ts:150:13
    at Array.forEach (<anonymous>)
    at Proxy.k (.../node_modules/vitest-fail-on-console/src/index.ts:148:7)
    at /Users/theo/dev/personal/scylla/frontend/web/src/testing/setup.ts:3:1
    at VitestExecutor.directRequest (.../node_modules/vite-node/dist/client.mjs:315:5)
    at VitestExecutor.cachedRequest (.../node_modules/vite-node/dist/client.mjs:159:14)
    at VitestExecutor.executeId (.../node_modules/vite-node/dist/client.mjs:143:12)
    at runSetupFiles (.../node_modules/@vitest/runner/dist/index.js:277:7)
    at collectTests (.../node_modules/@vitest/runner/dist/index.js:299:7)
```

Cheers,
Theo

**Comment by thomasbrodusch** [comment]
Thanks @theovier for raising this issue!

Edit:
Fixed in `v0.4.0` now available on `npm` enjoy @theovier 🥳
> https://github.com/thomasbrodusch/vitest-fail-on-console/tree/v0.4.0
